### ISSUE TITLE
Method setJson does not exist.

### ISSUE THREAD

**Issue by tnevel** [geXingW/lumen-request-validator#1]
BadMethodCallException in Macroable.php line 74:
Method setJson does not exist.
in Macroable.php line 74
at Request->__call('setJson', array(object(ParameterBag))) in ValidatorRequest.php line 106
at ValidatorRequest->_setData() in ValidatorRequest.php line 127

**Comment by geXingW** [comment]
@tnevel Sorry，麻烦提供下Lumen对应的版本号，和其他能够帮助我复现该问题的信息，我会尽快修复该问题。Thanks!

**Comment by tnevel** [comment]
lumen "5.3.*",
       "gexingw/lumen-request-validator": "^0.0.3"
       php 7.16

**Comment by geXingW** [comment]
@tnevel 非常感谢你的反馈。问题已经复现并修复，麻烦针对Lumen 5.3 使用最新的v0.0.4。
